---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - copy:
        src: /home/localuser/cvelist
        dest: /home/remoteuer/cvelist
    - shell: "cat cvelist | while read cves; do rpm -qa --changelog | grep -i $cves; done"
      register: remotehost_output
    - debug: msg="{{ remotehost_output.stdout_lines}}"
    - name: create local file
      lineinfile:
        dest:  "/home/localuser/reports/{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}.report"
        line: "Patched CVES for {{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
        create: true
      delegate_to: localhost
    - name: append output to local file
      lineinfile:
        dest: "/home/localuser/reports/{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}.report"
        line: "{{ remotehost_output.stdout_lines }}"
      delegate_to: localhost
        
