---
- hosts: all
  vars:
    setuserinfo:
      set-user-name: USERHERE
      set-user-password: PASS-HASH-HERE
      set-user-group: (insert wheel or leave blank)
  tasks:
    - name: user_management | check if user exists
      become: true
      shell: "id -u {{setuserinfo['set-user-name'] }}"
      register: checkuser_exists
      ignore_errors: true

    - name: user_management | update user password
      become: true
      user:
        name: "{{setuserinfo['set-user-name'] }}"
        password: "{{setuserinfo['set-user-password'] }}"
        update_password: always
        groups: "{{setuserinfo['set-user-group']}}"
        append: yes
      when: checkuser_exists.rc == 0

    - name: user_management | Create user
      become: true
      user:
        name: "{{setuserinfo['set-user-name'] }}"
        password: "{{setuserinfo['set-user-password'] }}"
        groups: "{{setuserinfo['set-user-group'] }}"
        append: yes
      when: checkuser_exists.rc !=0
